const char keymatrix[N_ROWS*N_COLS]={
KEY_NONE,		KEY_NONE,	KEY_RIGHT,		KEY_RIGHTBRACE,	KEY_MINUS,		KEY_P,			KEY_INSERT,	KEY_J,		KEY_U,		KEY_T,		KEY_3,		KEY_NONE,		KEY_Q,		KEY_NONE,		KEY_RIGHTCTRL,	KEY_NONE,		KEY_1,			KEY_NONE,
KEY_NONE,		KEY_DELETE,	KEY_DOWN,		KEY_LEFT,		KEY_DOLLAR,		KEY_APOSTROPHE,	KEY_PROPS,	KEY_SPACE,	KEY_B,		KEY_V,		KEY_NONE,	KEY_RIGHTALT,	KEY_Z,		KEY_NONE,		KEY_NONE,		KEY_NONE,		KEY_NONE,		KEY_NONE,
KEY_PAGEDOWN,	KEY_NONE,	KEY_SEMICOLON,	KEY_HOME,		KEY_SLASH,		KEY_DOT,		KEY_NONE,	KEY_COMMA,	KEY_N,		KEY_F,		KEY_C,		KEY_LEFTALT,	KEY_X,		KEY_NONE,		KEY_NONE,		KEY_NONE,		KEY_A,			KEY_NONE,
KEY_NONE,		KEY_PAGEUP,	KEY_BACKSLASH,	KEY_UP,			KEY_NONE,		KEY_EURO,		KEY_NONE,	KEY_M,		KEY_H,		KEY_G,		KEY_D,		KEY_NONE,		KEY_S,		KEY_NONE,		KEY_NONE,		KEY_RIGHTSHIFT,	KEY_CAPSLOCK,	KEY_NONE,
KEY_NONE,		KEY_NONE,	KEY_ENTER,		KEY_NONE,		KEY_LEFTBRACE,	KEY_L,			KEY_NONE,	KEY_K,		KEY_Y,		KEY_R,		KEY_E,		KEY_NONE,		KEY_W,		KEY_LEFTMETA,	KEY_NONE,		KEY_NONE,		KEY_TAB,		KEY_NONE,
KEY_NONE,		KEY_NONE,	KEY_BACKSPACE,	KEY_EQUAL,		KEY_0,			KEY_O,			KEY_NONE,	KEY_I,		KEY_7,		KEY_5,		KEY_4,		KEY_NONE,		KEY_2,		KEY_NONE,		KEY_LEFTCTRL,	KEY_NONE,		KEY_GRAVE,		KEY_NONE,
KEY_NONE,		KEY_NONE,	KEY_PAUSE,		KEY_SYSRQ,		KEY_F12,		KEY_9,			KEY_NONE,	KEY_F8,		KEY_8,		KEY_6,		KEY_F4,		KEY_NONE,		KEY_F2,		KEY_NONE,		KEY_NONE,		KEY_LEFTSHIFT,	KEY_F1,			KEY_NONE,
KEY_NONE,		KEY_NONE,	KEY_END,		KEY_NONE,		KEY_F11,		KEY_F10,		KEY_NONE,	KEY_F9,		KEY_F7,		KEY_F6,		KEY_F5,		KEY_NONE,		KEY_F3,		KEY_NONE,		KEY_NONE,		KEY_NONE,		KEY_ESC,		KEY_NONE
};
